export const AUCTION_TYPES = [
    { value: "Copart", label: "Copart" },
    { value: "IAAI", label: "IAAI" }, // User HTML has Copart and IAAI separately in first select
    { value: "Manheim", label: "Manheim" },
    { value: "Adesa", label: "Adesa" },
];

export const VEHICLE_TYPES_AUCTION = [
    { value: "standard", label: "მსუბუქი ავტომობილი" },
    { value: "heavy", label: "მძიმე ტექნიკა" },
];

export const LOGISTICS_AUCTION_TYPES = [
    { value: "Copart", label: "Copart/IAAI" },
    { value: "Manheim", label: "Manheim/Adesa" },
];

export const DESTINATION_PORTS = [
    { value: "POTI", label: "ფოთი" },
    { value: "KLAIPEDA", label: "კლაიპედა" },
    { value: "ODESSA", label: "ოდესა" },
    { value: "Jebel Ali", label: "Jebel Ali" },
];

export const VEHICLE_CATEGORIES = [
    { value: "Sedan", label: "სედანი" },
    { value: "Bike", label: "მოტოციკლი" },
    { value: "Small SUV", label: "პატარა ჯიპი" },
    { value: "Big SUV", label: "დიდი ჯიპი" },
    { value: "Pickup", label: "პიკაპი" },
    { value: "Van", label: "მინივენი" },
    { value: "Big Van", label: "სამარშუტო ტაქსი" },
];

export const FUEL_TYPES = [
    { value: "Gasoline", label: "შიდაწვის" },
    { value: "Hybrid", label: "ჰიბრიდი" },
    { value: "Electro", label: "ელექტრო" },
];

export const INSURANCE_OPTIONS = [
    { value: "Yes", label: "კი" },
    { value: "No", label: "არა" },
];

// Full list from user HTML
export const USA_CITIES = [
    "AL-ATHENS", "AL-BESSEMER", "AL-BIRMINGHAM", "AL-BLANDED SALES", "AL-DOTHAN", "AL-EIGHT MILE", "AL-HEADLAND", "AL-HUEYTOWN", "AL-HUNTSVILLE", "AL-MOBILE", "AL-MONTGOMERY", "AL-MOODY", "AL-TANNER",
    "AR-CONWAY", "AR-FAYETTEVILLE", "AR-LINCOLN", "AR-LITTLE ROCK", "AR-PRAIRIE GROVE", "AR-SCOTT",
    "AZ-CHANDLER", "AZ-PHOENIX", "AZ-TOLLESON", "AZ-TUCSON",
    "CA - ADELANTO", "CA - REDDING", "CA-ACE PARIS", "CA-ADESA SAN JOSE", "CA-ANAHEIM", "CA-ANTELOPE", "CA-BAKERSFIELD", "CA-BAY POINT", "CA-CALIFORNIA MANHEIM", "CA-CARSON", "CA-CENTRAL CALIFORNIA", "CA-COLTON", "CA-EAST BAY", "CA-FAIRFIELD", "CA-FONTANA", "CA-FREMONT", "CA-FRESNO", "CA-GARDENA", "CA-GOLDENGATE", "CA-HAYWARD", "CA-HESPERIA", "CA-HIGH DESERT", "CA-LONG BEACH", "CA-LOS ANGELES", "CA-MARTINEZ", "CA-NAPA", "CA-NORTH HOLLYWOOD", "CA-RANCHO CORDOVA", "CA-RANCHO CUCAMONGA", "CA-RIO LINDA", "CA-RIVERSIDE", "CA-SACRAMENTO", "CA-SAN BERNARDINO", "CA-SAN DIEGO", "CA-SAN FRANCISKO BAY", "CA-SAN JOSE", "CA-SAN MARTIN", "CA-SAN VALLEY", "CA-SO SACRAMENTO", "CA-SOUTHETN CALIFORNIA", "CA-VALLEJO", "CA-VAN NUYS",
    "CO-BRIGHTON", "CO-COLORADO SPRINGS", "CO-COMMERCE CITY", "CO-DELTA", "CO-DENVER", "CO-DENVER CENTRAL", "CO-DENVER EAST", "CO-DENVER SOUTH", "CO-WESTERN COLORADO",
    "CT-EAST WINDSOR", "CT-HARTFORD SOUTH", "CT-MIDDLETOWN", "CT-NEW BRITAIN",
    "DE-NEW CASTLE", "DE-SEAFORD",
    "FL-CLEARWATER", "FL-DAYTONA BEACH", "FL-FORT LAUDERDALE", "FL-FORT MAYERS", "FL-FT PIERCE", "FL-HOMESTEAD", "FL-JACKSONVILLE", "FL-LAKELAND", "FL-MIAMI CENTRAL", "FL-MIAMI NORTH", "FL-MIAMI SOUTH", "FL-MIDWAY", "FL-NORTH FORT MAYERS", "FL-OCALA", "FL-OPA LOCKA", "FL-ORLANDO", "FL-ORLANDO NORTH", "FL-PALMETTO", "FL-PENSACOLA", "FL-PUNTA GORDA", "FL-REVERVIEW", "FL-SANFORD", "FL-ST.PETE CLEARWATER", "FL-TALLAHASSEE", "FL-TAMPA", "FL-TAMPA SOUTH", "FL-WEST PALM BEACH",
    "GA-ACWORTH", "GA-ATLANTA EAST", "GA-ATLANTA NORTH", "GA-ATLANTA SOUTH", "GA-ATLANTA WEST", "GA-AUGUSTA", "GA-AUSTELL", "GA-CARTERSVILLE", "GA-ELLENWOOD", "GA-FAIRBURN", "GA-GAINESVILLE", "GA-LAKE CITY", "GA-LOGANVILLE", "GA-MACON", "GA-MANHEIM GEORGIA", "GA-SAVANNAH", "GA-TIFTON", "GA-WINDER",
    "IA-CRASHED TOYS ELDRIDGE", "IA-DAVENPORT", "IA-DES MOINES", "IA-WAUKEE",
    "ID-BOISE", "ID-NAMPA",
    "IL-AURORA", "IL-CHICAGO HEIGHTS", "IL-CHICAGO NORTH", "IL-CHICAGO SOUTH", "IL-CHICAGO WEST", "IL-EAST DUNDEE", "IL-ELGIN", "IL-GRANITE SITY", "IL-LINCOLN", "IL-MANHEIM ARENA ILLINOIS", "IL-MANHEIM CHICAGO", "IL-MARKHAM", "IL-PEKIN", "IL-PEORIA", "IL-SCHAUMBURG", "IL-SOUTHERN ILLINOIS", "IL-SPECIALTY DIVISION", "IL-ST.LOUIS", "IL-WHEELING",
    "IN-CICERO", "IN-FORT WAYNE", "IN-HAMMOND", "IN-HARTFORD CITY", "IN-INDIANAPOLIS", "IN-MANHEIM LOUISVILLE", "IN-SOUTH BEND",
    "KS-KANSAS CITY", "KS-WICHITA",
    "KY-ASHLAND", "KY-BOWLING GREEN", "KY-EARLINGTON", "KY-EMINENCE", "KY-KENTUCKY", "KY-LAWRENCEBURG", "KY-LEXINGTON", "KY-LOUSHVILLE", "KY-WALTON",
    "LA-BATON ROUGE", "LA-COVINGTON", "LA-GREENWELL SPRINGS", "LA-GREENWOOD", "LA-LAFAYETTE", "LA-LIVINGSTON", "LA-NEW ORLEANS", "LA-NEW ORLEANS EAST", "LA-SHREVEPORT",
    "MA-BOSTON SHIRLEY", "MA-FREETOWN", "MA-MANHEIM NEW ENGLAND", "MA-NORTH BELLERICA", "MA-NORTH BOSTON", "MA-SOUTH BOSTON", "MA-TAUNTON", "MA-TEMPLETON", "MA-WEST WARREM",
    "MD-BALTIMORE", "MD-BRANDYWINE", "MD-DUNDALK", "MD-FINKSBURG", "MD LAUREL", "MD-MANHEIM BALTIMORE", "MD-METRO DC", "MD-ROSEDALE", "MD-SALISBURG", "MD-WALDORF", "MD-WASHINGTON DC",
    "ME-GORHAM/PORTLAND", "ME-LYMAN", "ME-ORONO", "ME-WINDHAM",
    "MI-BAY CITY", "MI-BELLEVILLE", "MI-BYRON CENTER", "MI-DAVISON", "MI-DETROIT", "MI-FLINT", "MI-GRAND LAKES", "MI-GRAND REPIDS", "MI-IONIA", "MI-KINCHELOE", "MI-LANSING", "MI-PORTLAND", "MI-WOODAHAVEN",
    "MN-AVON", "MN-CRASHEDTOYS EAST BETHEL", "MN-FRIDLAY", "MN-HAM LAKE", "MN-MINNEAPOLIS", "MN-MINNEAPOLIS NORTH", "MN-ST.CLOUD", "MN-ST.PAUL",
    "MO- KANSAS CITY", "MO-BRIDGESTON", "MO-COLUMBIA", "MO-KANSAS CITY", "MO-MANHEIM KANSAS CITY", "MO-ROGERSVILLE", "MO-SIKESTON", "MO-SPRINGFIELD", "MO-ST.LOUIS",
    "MS-GRENADA", "MS-GULF COAST", "MS-JACKSON", "MS-MISSISSIPI", "MS-MOSS POINT",
    "MT-BILLINGS", "MT-HELENA", "MT-MISSOULA",
    "NC-ASHVILLE", "NC-CHARLOTTE", "NC-CHINA GROVE", "NC-CLAYTON", "NC-CONCORD", "NC-FLETCHER", "NC-GRAHAM", "NC-GREENSBORO", "NC-High Point", "NC-LUMBERTON", "NC-MEBANE", "NC-MOCKSVILLE", "NC-NORTH CAROLINA", "NC-RALEIGH", "NC-STATESVILLE", "NC-WILMINGTON",
    "ND-FARGO", "ND-WEST FARGO",
    "NE-GREENWOOD", "NE-LINCOLN", "NE-OMAHA", "NE-SPRINGFIELD",
    "NH-CANDIA", "NH-MANCHESTER", "NH-SALEM",
    "NJ-AVENEL NEW JERSEY", "NJ-CARTERET", "NJ-CENTRAL NEW JERSEY", "NJ-ENGLISHTOWN", "NJ-FAIRFIELD", "NJ-GLASSBORO EAST", "NJ-HILLSBOROUGH", "NJ-METRO SKY LINE", "NJ-MORGANVILLE", "NJ-NEW JERSEY", "NJ-NORTHERN NEW JERSEY", "NJ-SOMERVILLE", "NJ-SOUTHERN NEW JERSEY", "NJ-TRENTON", "NJ-TURNERSVILLE", "NJ-WINDSOR",
    "NM-ALBUQERQ",
    "NV-HENDERSON", "NV-LAS VEGAS", "NV-MACCARRAN", "NV-MANHEIM NEVADA", "NV-RENO",
    "NY-ALBANY", "NY-BERGEN", "NY-BROOKHAVEN", "NY-BUFFALO", "NY-CENTRAL SQUARE", "NY-CICERO", "NY-LEROY", "NY-LONG ISLAND", "NY-MARLBORO", "NY-MEDFORD", "NY-NEWBURGH", "NY-ROCHESTER", "NY-ROCK TAVERN", "NY-SCHENECTADY", "NY-SYRACUSE",
    "OH-AKRON CANTON", "OH-AMELIA", "OH-CINCINATTI", "OH-CINCINATTI SOUTH", "OH-CLEVELAND EAST", "OH-CLEVELAND ELIZABETH", "OH-CLEVELAND WEST", "OH-CLEVELAND/LORAIN", "OH-COLUMBIA STATION", "OH-COLUMBUS", "OH-DAYTONA", "OH-GROVE CITY", "OH-LORAIN", "OH-MANHEIM CINCINATI", "OH-MANHEIM OHIO GROVE CTY", "OH-MORAINE", "OH-NEW PHILADELPHIA", "OH-NORTHFIELD", "OH-WEST CHESTER",
    "OK-OKLAHOMA CITY", "OK-TULSA",
    "OR-EUGENE", "OR-PORTLAND", "OR-PORTLAND NORTH", "OR-PORTLAND WEST", "OR-POTLAND SOUTH-WOODBURN",
    "PA-ADAMSBURG", "PA-ALIQUIPPA", "PA-ALTOONA", "PA-BRIDGEPORT", "PA-CHALFONT", "PA-CHAMBERSBURG", "PA-CONSHOHOCKEN", "PA-EAST FREEDOM", "PA-EBENSBURG", "PA-ERIE", "PA-GARLAND", "PA-GIBSONIA", "PA-GRANTVILLE", "PA-HARRISBURG", "PA-PENNSBURG", "PA-PHILADELPHIA", "PA-PHILADELPHIA EAST", "PA-PITTSBURG", "PA-PITTSBURG EAST", "PA-PITTSBURG NORTH", "PA-PITTSBURG SOUTH", "PA-PITTSON", "PA-SCRANTON", "PA-WEST MIFFLIN", "PA-YORK HAVEN", "PA-YORK SPRINGS",
    "RI-EXETER", "RI-PROVIDENCE",
    "SC-CHARLESTON", "SC-COLUMBIA", "SC-GASTON", "SC-GREENVILLE", "SC-GREER", "SC-LEXINGTON", "SC-RAVENEL", "SC-SIMPSONVILLE", "SC-SPARTANBURG",
    "SD-SIOUX FALLS",
    "TN-CHATTANOOGA", "TN-KNOXVILLE", "TN-LEBANON", "TN-MEDISONVILLE", "TN-MEMPHIS", "TN-NASHVILLE", "TN-NASHVILLE BLANDED SALES", "TN-OLD HISKORY 37138", "TN-TENNESSE",
    "TX-ABILENE", "TX-AMARILLO", "TX-ANDREWS", "TX-ANTHONY", "TX-AUSTIN", "TX-CORPUS CHRISTI", "TX-DALE", "TX-DALLAS", "TX-DALLAS SOUTH", "TX-EL PASO", "TX-FORT WORTH NORTH", "TX-FT.WORTH", "TX-GRAND PRAIRIE", "TX-HASLET", "TX-HAWLAY", "TX-HOUSTON", "TX-HOUSTON NORTH", "TX-KLAIPEDA", "TX-LONGVIEW", "TX-LUBBOCK", "TX-LUFKIN", "TX-MACALLEN", "TX-MANHEIM TEXAS", "TX-MERCEDES", "TX-NEW BRAUNFELS", "TX-PERMIAN BASIN", "TX-SAN ANTONIO", "TX-TEMPLE", "TX-WACO", "TX-WILMER",
    "UT-FARR WEST", "UT-MANHEIM UTAH", "UT-NORTH SALT LAKE", "UT-OGDEN", "UT-SALT LAKE CITY", "UT-WOODS CROSS",
    "VA TIDEWATER", "VA-ASHLAND", "VA-CHATHAM", "VA-CULPEPER", "VA-DANVILLE", "VA-FREDERICKBURG", "VA-HAMPTON", "VA-NORTHEN VIRGINIA", "VA-PULASKI", "VA-RICHMOND", "VA-SANDSTON", "VA-SUFFOLK", "VA-YORKTOWN",
    "VT-BURLINGTON", "VT-ESSEX", "VT-ORLEANS", "VT-RUTLAND",
    "WA-AIRWAY HEIGHTS", "WA-ARLINGTON", "WA-GRAHAM", "WA-NORTH SEATTLE", "WA-PASCO", "WA-SEATTLE", "WA-SEATTLE SOUTH", "WA-SPOKANE", "WA-SPOKANE VALLEY", "WA-SUMNER", "WA-TUKWILA",
    "WI-APPLETON", "WI-CUDAHY", "WI-MADISON", "WI-MILWAUKEE", "WI-PORTAGE", "WI-SUSSEX",
    "WV-BUCKHANNON", "WV-CHARLESTON", "WV-HURRICANE", "WV-SHADY SPRING",
    "WY - CASPER"
];
