export const API_ENDPOINTS = {
    AUTH: {
        REGISTER: '/auth/register',
        REGISTER_COMPANY: '/auth/register-company',
        LOGIN: '/auth/login',
        LOGOUT: '/auth/logout',
        LOGOUT_ALL: '/auth/logout-all',
        REFRESH: '/auth/refresh',
        ME: '/auth/me',
        VERIFY_EMAIL: '/auth/verify-email',
        RESEND_VERIFICATION: '/auth/resend-verification',
        FORGOT_PASSWORD: '/auth/forgot-password',
        RESET_PASSWORD: '/auth/reset-password',
        CREATE_TOUR_AGENT: '/auth/tour-agents',
        CLAIM_ROLE: '/auth/claim-role',
    },
    USERS: {
        CREATE: '/users',
        ME: '/users/me',
        UPDATE_ME: '/users/me',
        DELETE_ME: '/users/me',
    },
    TOURS: {
        LIST: '/tours',
        MY_TOURS: '/me/tours',
        CREATE: '/tours',
        GET: (id: string) => `/tours/${id}`,
        UPDATE: (id: string) => `/tours/${id}`,
        DELETE: (id: string) => `/tours/${id}`,
        UPLOAD_IMAGE: (id: string) => `/tours/${id}/images`,
    },
    COMPANIES: {
        LIST: '/companies',
        MY_COMPANY: '/companies/my',
        GET: (id: string) => `/companies/${id}`,
        UPDATE: (id: string) => `/companies/${id}`,
        DELETE: (id: string) => `/companies/${id}`,
        TOURS: (id: string) => `/companies/${id}/tours`,
        PHOTOS: (id: string) => `/companies/${id}/photos`,
        DELETE_PHOTO: (id: string, photoId: string) => `/companies/${id}/photos/${photoId}`,
    },
    DRIVERS: {
        LIST: '/drivers',
        MY: '/drivers/my',
        GET: (id: string) => `/drivers/${id}`,
        UPDATE: (id: string) => `/drivers/${id}`,
        DELETE: (id: string) => `/drivers/${id}`,
        PHOTOS: (id: string) => `/drivers/${id}/photos`,
        DELETE_PHOTO: (id: string, photoId: string) => `/drivers/${id}/photos/${photoId}`,
    },
    GUIDES: {
        LIST: '/guides',
        MY: '/guides/my',
        GET: (id: string) => `/guides/${id}`,
        UPDATE: (id: string) => `/guides/${id}`,
        DELETE: (id: string) => `/guides/${id}`,
        PHOTOS: (id: string) => `/guides/${id}/photos`,
        DELETE_PHOTO: (id: string, photoId: string) => `/guides/${id}/photos/${photoId}`,
    },
    LOCATIONS: {
        LIST: '/locations',
        GET: (id: string) => `/locations/${id}`,
        CREATE: '/locations',
        UPDATE: (id: string) => `/locations/${id}`,
        DELETE: (id: string) => `/locations/${id}`,
    },
    PRESENCE: {
        ME: '/presence/me',
        USER: (userId: string) => `/presence/${userId}`,
        MULTIPLE: '/presence/multiple',
        ONLINE_ALL: '/presence/online/all',
        STATS: '/presence/stats',
    },
    NOTIFICATIONS: {
        LIST: '/notifications',
        UNREAD_COUNT: '/notifications/unread-count',
        MARK_READ: (id: string) => `/notifications/${id}/read`,
        MARK_ALL_READ: '/notifications/read-all',
        DELETE: (id: string) => `/notifications/${id}`,
    },
    INQUIRIES: {
        LIST: '/inquiries',
        RECEIVED: '/inquiries/received',
        CREATE: '/inquiries',
        GET: (id: string) => `/inquiries/${id}`,
        RESPOND: (id: string) => `/inquiries/${id}/respond`,
    },
    CHATS: {
        LIST: '/chats',
        DIRECT: '/chats/direct',
        GET: (id: string) => `/chats/${id}`,
        MESSAGES: (chatId: string) => `/chats/${chatId}/messages`,
        SEND_MESSAGE: (chatId: string) => `/chats/${chatId}/messages`,
        MARK_READ: (chatId: string) => `/chats/${chatId}/read`,
    },
    SEARCH: {
        MAIN: '/search',
        LOCATIONS: '/search/locations',
        LOCATION_STATS: (id: string) => `/search/locations/${id}/stats`,
    },
} as const;
