export const ROUTES = {
    HOME: '/',
    LOGIN: '/login',
    REGISTER: '/register',
    COMPANY_REGISTER: '/register-company',
    VERIFY_EMAIL: '/verify-email',
    VERIFY_EMAIL_PENDING: '/verify-email-pending',
    FORGOT_PASSWORD: '/forgot-password',
    RESET_PASSWORD: '/reset-password',
    DASHBOARD: '/dashboard',
    PROFILE: '/dashboard/profile',
    SETTINGS: '/dashboard/settings',
    CREATE_AGENT: '/dashboard/create-agent',
    TOURS: {
        LIST: '/tours',
        DETAILS: (id: string) => `/tours/${id}`,
        MY_TOURS: '/my-tours',
        CREATE: '/dashboard/tours/create',
        EDIT: (id: string) => `/tours/${id}/edit`,
    },
    EXPLORE: '/explore',
    EXPLORE_TOURS: '/explore/tours',
    EXPLORE_HOTELS: '/explore/hotels',
    EXPLORE_COMPANIES: '/explore/companies',
    EXPLORE_GUIDES: '/explore/guides',
    EXPLORE_DRIVERS: '/explore/drivers',
    BECOME_PARTNER: '/dashboard/become-partner',
    COMPANY_MANAGEMENT: '/dashboard/company',
    OPERATIONS: {
        ROOT: '/dashboard/operations',
        AGENTS: '/dashboard/operations/agents',
        TOURS: '/dashboard/operations/tours',
    },
    ADMIN: {
        ROOT: '/dashboard/admin',
        LOCATIONS: '/dashboard/admin/locations',
        USERS: '/dashboard/admin/users',
    },
    INQUIRIES: {
        ROOT: '/dashboard/inquiries',
        SENT: '/dashboard/inquiries/sent',
        RECEIVED: '/dashboard/inquiries/received',
        DETAILS: (id: string) => `/dashboard/inquiries/${id}`,
        CREATE: '/dashboard/inquiries/create',
    },
    CHATS: {
        ROOT: '/dashboard/chats',
        DETAILS: (id: string) => `/dashboard/chats/${id}`,
    },
} as const;
